using CMCSApp1.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;

namespace CMCSApp1.Services
{
    public class InvoiceGenerationService
    {
        public string GenerateInvoice(Claim claim)
        {
            var sb = new StringBuilder();

            sb.AppendLine("<html><body>");
            sb.AppendLine("<h1>Invoice for Claim</h1>");
            sb.AppendLine($"<h2>Lecturer: {claim.Lecturer.Name}</h2>");
            sb.AppendLine($"<p><strong>Hours Worked:</strong> {claim.HoursWorked}</p>");
            sb.AppendLine($"<p><strong>Hourly Rate:</strong> R{claim.HourlyRate}</p>");
            sb.AppendLine($"<p><strong>Total Payment:</strong> R{claim.TotalPayment}</p>");
            sb.AppendLine($"<p><strong>Notes:</strong> {claim.Notes}</p>");
            sb.AppendLine("<p>Invoice generated by the Contract Monthly Claim System.</p>");
            sb.AppendLine("</body></html>");

            return sb.ToString(); // Return the HTML content of the invoice
        }
    }
}
